### ISSUE TITLE
No leading backslash in imports

### ISSUE THREAD

**Issue by szepeviktor** [phplrt/phplrt#10]
PHP docs says

>    the leading backslash is unnecessary and not recommended, as import names must be fully qualified, and are not processed relative to the current namespace

https://www.php.net/manual/en/language.namespaces.importing.php

Please consider generating code that excludes the leading backslash.

https://github.com/phplrt/phplrt/blob/master/src/Compiler/tests/resources/output.php#L3

**Comment by SerafimArts** [comment]
Fixed along with codestyle fixes in https://github.com/phplrt/phplrt/commit/dd5d357df580349d51ad88b10755d72acaf34dd2

**Comment by szepeviktor** [comment]
Thank you.
