### ISSUE TITLE
Ability to create/rename a node from within a rule

### ISSUE THREAD

**Issue by kitbs** [phplrt/phplrt#11]
Hi there!

I have recently been experimenting with Hoa Compiler but as it's not actively managed any more, I have started looking for alternatives and found your project. I am struggling a bit with the missing documentation but I am liking what I see so far.

One feature of Hoa that I can't seem to replicate in PHP LRT is the ability to [create a node from within a rule](https://hoa-project.net/En/Literature/Hack/Compiler.html#:~:text=to%20create%20a%20node%20node%20in%20the%20resulting%20tree). For example, in Hoa I would be able to write this:

```
operation:
    ::not:: comparison_operation() #not | comparison_operation()
```

This wraps the whole comparison operation in a `#not` node if the `not` token is found, or otherwise just returns the comparison operation.

Although the syntax is very similar, I cannot replicate this in PHP LRT, for example, this fails with an unexpected "#" error:

```
Operation
    :
    ::T_NOT:: ComparisonOperation() #Not | ComparisonOperation()
    ;
```

The only solution I can currently find is to duplicate any of my rules that need this feature with a `#` version, like this:

```
Operation
    :
    NotOperation() | ComparisonOperation()
    ;

#NotOperation
    :
    ::T_NOT:: ComparisonOperation()
    ;
```

But this doubles the size and complexity of my grammar, and in some cases is just not workable.

I did see that there was a "Rename" syntax that seemed to be supported in the [earlier version of your grammar](https://github.com/phplrt/phplrt/blob/1.x/src/Compiler/Resources/pp2/grammar.pp2#L81) but I can't find anything similar in the newer version.

Is there any intention to bring back support for this feature, or can you suggest an alternative for what I am trying to achieve?

Thanks!

**Comment by SerafimArts** [comment]
Hello! This functionality has been removed because in later versions, the functionality of user (custom) nodes appeared, which are not tied to names in any way: https://phplrt.org/#/compiler/code#php-code

For example:
```php
NotOperation -> {
    return new NotOperationNode($children[0]);
}
    : ::T_NOT:: ComparisonOperation()
    ;
```

Thus, you are no longer tied to a specific type of AST (and node names) and can create your own nodes.

Here you can find a more complete example: https://github.com/BicEngine/Preprocessor/blob/master/resources/expression/grammar.pp2

**Comment by SerafimArts** [comment]
Closed due to long lack of answer. @kitbs If this issue is still relevant, please notify.
