### ISSUE TITLE
PHP8 Support

### ISSUE THREAD

**Issue by tpetry** [phplrt/phplrt#12]
Since the Hoa compiler is no longer maintained I found some alternatives in their issues. The one that looks best from the surface really seems to be your version ❤️.

The problem why I have to switch is that the Hoa compiler is now raising warnings that certain used PHP constructs will soon not be supported anymore. But i can't install your package because your versions of `symplify/monorepo-builder` don't support PHP 8. Only starting with version 8 of `symplify/monorepo-builder` PHP 8 will be supported. 

I forced composer to install your package and ran your unit tests with PHP 8 and everything passes, so your code seems to have no problem with PHP 8. Could you upgrade the `symplify/monorepo-builder` to support php 8?

**Comment by SerafimArts** [comment]
Done: https://github.com/phplrt/phplrt/releases/tag/3.1.3

I apologize. When I added support for PHP 8, not all packages still supported it, so I had to use `--ignore-platform-reqs` flag, and then I just forgot to update them.
