### ISSUE TITLE
Recursive grammar

### ISSUE THREAD

**Issue by lezhnev74** [phplrt/phplrt#16]
Hey! I wonder what is the right way to define an expression recursively? 
This code snippet exhausts all the memory (php 8.1):
```php
<?php

namespace Hack;

use Phplrt\Compiler\Compiler;

include "vendor/autoload.php";

$compiler = new Compiler();
$compiler->load(
    <<<EBNF

%skip whitespace \s+

%token operand \d+
%token operator [+-]

#expr : 
    expr() <operator> expr()
    | <operand>
 ;

EBNF
);

$compiler->parse("10 + 2"); // <-- fails here
```

**Comment by SerafimArts** [comment]
Yea, cause `expr = expr`. This is a grammar error for the phplrt parser algorithm (and any "reverse descent" algos).

If you follow the work of the parser, you can see the following call stack:
- goto `#expr`
- exec `expr()`
- goto `#expr`
- exec `expr()`
- etc...

Use this grammar instead (for example):
```
#expr
  : <operand> (<operator> expr())?
  ;
```

Or this:
```
#expr
  : <operand> (<operator> expr())*
  ;
```

**Comment by lezhnev74** [comment]
Thanks a lot, that makes total sense now! Yeah left recursion is tricky, I saw Terence Parr claimed he had it in antlr. Anyways this tool opens so many new possibilities to php community. Keep it up :+1:
