### ISSUE TITLE
The math expression example https://phplrt.org/docs/examples/simple-math does not work

### ISSUE THREAD

**Issue by RoNoLo** [phplrt/phplrt#19]
### Description

There is no problem with the code. I just checking the documentation to learn and evaluate the library.

### How To Reproduce

Use the grammar as file from here https://phplrt.org/docs/examples/simple-math and execute the code provided in the example. First the expected XML seems wrong and secondly a understandable error about an enexpected symbol is thrown.

Next Phplrt\Parser\Exception\UnrecognizedTokenException: Syntax error, unrecognized "*"
   1. | 2 + 2 * 2
      |       ^ in ...\vendor\phplrt\phplrt\src\Parser\src\Exception\UnrecognizedTokenException.php:44
Stack trace:

**Comment by SerafimArts** [comment]
Yea. There is a mistake/typo in the documentation regarding the expression `2 + 2 * 2`. The correct version should look like `2 + 2 - 10 + 1000`

**Comment by SerafimArts** [comment]
Done
