### ISSUE TITLE
Visitor that alters AST - need advice

### ISSUE THREAD

**Issue by guiled** [phplrt/phplrt#2]
### Description
I am trying to make a Visitor that alters the AST structure itself (Yes, I DO need it…)
I managed to write one that do the job but it doesn't satisfy me…
```php
class ASTAlterer extends \Phplrt\Visitor\Visitor
{
    public function before(iterable $node): ?iterable
    {
        if (conditionToAlterNode($node)) {
                $node = alterStructure($node);
        }
        $result = [];
        foreach ($node as $k => $n) {
            $result[$k] = $this->before($n);
        }
        if (is_array($node)) {
            return $result;
        }
        $node->setChildren($result);
        return $node;
    }
}
$result = (new \Phplrt\Visitor\Traverser([new ASTAlterer(), new ExampleVisitor()]))->traverse($ast);
```
What I don't like in my solution is the array `$result` it creates and set to the node with a ugly custom Node method called `$node->setChildren()`.

Do you have any suggestion to make this more appropriate ?

### Environment

- Phplrt Version: 3.0.2
- PHP Version: 7.4

**Comment by SerafimArts** [comment]
The `before` method is already applied for each element of the node, why you call it recursively?

**Comment by guiled** [comment]
I don't know why but I am unable to see before() applied on each element.
(the following visitor display only one line
```php
class ASTAlterer extends \Phplrt\Visitor\Visitor
{
    public function before(iterable $node): ?iterable
    {
        echo 'Analyse', PHP_EOL;
        return null;
    }
}
$result = (new \Phplrt\Visitor\Traverser([new ASTAlterer(), new ExampleVisitor()]))->traverse($ast);
```

Here https://github.com/phplrt/phplrt/blob/master/src/Visitor/src/Executor.php#L110
The `execute()` method runs once the `before()` method
And here https://github.com/phplrt/phplrt/blob/master/src/Visitor/src/Executor.php#L123-L127
The `before()`method runs once each visitor on the given ast.

I must have missed something.

**Comment by SerafimArts** [comment]
Do you implement the NodeInterface in ur ast nodes?

**Comment by guiled** [comment]
Yes, the nodes implements NodeInterface and return an iterator of the children when necessary (except for final node of course).

**Comment by SerafimArts** [comment]
In this case, I don’t know what the problem is. The entire visitor is covered in tests partially taken from nikic/php-parser.

I suggest creating an issue with a task to document this part of the functional (traverser/visitor). In this case, perhaps you will find the problem yourself, focusing on examples and description. And there on the site the layout broke due to a bug in chrome, it will also need to be fixed... +)

**Comment by guiled** [comment]
Is there any working example I could take a look at ?

**Comment by guiled** [comment]
Hi !

#Code 
```php
<?php
require 'vendor/autoload.php';

use Phplrt\Compiler\Compiler;

$compiler = new Compiler();
$compiler->load(<<<EBNF

      %token T_DIGIT          \d
      %token T_PLUS           \+
      %token T_MINUS          \-
      %token T_POW            \*
      %token T_DIV            /
      %skip  T_WHITESPACE     \s+

      #Expression :
          <T_DIGIT> (Operator() <T_DIGIT>)*
      ;

      #Operator
      : <T_PLUS>
      | <T_MINUS>
      | <T_POW>
      | <T_DIV>
      ;
      EBNF);

$ast = $compiler->parse('3 + 7 + 9');

echo $ast, PHP_EOL;

$visitors = [
    new class extends \Phplrt\Visitor\Visitor {

        public function before(iterable $nodes): ?iterable
        {
            foreach ($nodes as $n) {
                echo 'before ', PHP_EOL;
            }
            return null;
        }

        /**
         * {@inheritDoc}
         */
        public function enter(Phplrt\Contracts\Ast\NodeInterface $node)
        {
            echo 'enter ', PHP_EOL;
            return null;
        }

        /**
         * {@inheritDoc}
         */
        public function leave(Phplrt\Contracts\Ast\NodeInterface $node)
        {
            echo 'leave ', PHP_EOL;
            return null;
        }

        /**
         * {@inheritDoc}
         */
        public function after(iterable $nodes): ?iterable
        {
            foreach ($nodes as $n) {
                echo 'after ', PHP_EOL;
            }
            return null;
        }
    }];

(new \Phplrt\Visitor\Traverser($visitors))->traverse($ast);
```

#Output
```
<Expression offset="0">
    <T_DIGIT offset="0">3</T_DIGIT>
    <Operator offset="2">
        <T_PLUS offset="2">+</T_PLUS>
    </Operator>
    <T_DIGIT offset="4">7</T_DIGIT>
    <Operator offset="6">
        <T_PLUS offset="6">+</T_PLUS>
    </Operator>
    <T_DIGIT offset="8">9</T_DIGIT>
</Expression>
before 
enter 
enter 
leave 
enter 
leave 
leave 
after 
```

As we can see here, there is only one before call and one after call.
On the other side, there are many enter and leave (corresponding with the AST nodes)

**Comment by guiled** [comment]
Hello,

I've read in  nikic/PHP-Parser that before is triggered only once : at the visit beginning (it's like an Visit initialization). So, I think the use of before in my first question is not appropriate
