### ISSUE TITLE
Static Analysis Errors

### ISSUE THREAD

**Issue by SerafimArts** [phplrt/phplrt#7]
It is necessary to fix the errors of the static analysis found in PR https://github.com/phplrt/phplrt/pull/6

CI Job: https://travis-ci.org/github/phplrt/phplrt/jobs/702932253

**Comment by szepeviktor** [comment]
This project is **too** scientific for me, I'm just a janitor of apps.

Add `string` to src/Lexer/src/Exception/UnexpectedStateException.php:28

**Comment by SerafimArts** [comment]
> This project is too scientific for me, I'm just a janitor of apps.

Do not worry, I assigned this issue to myself

> Add string to src/Lexer/src/Exception/UnexpectedStateException.php:28

A state can be either a string or a numerical (int) index.

**Comment by szepeviktor** [comment]
> A state can be either a string or a numerical (int) index.

You see?? I'm just a janitor of apps.

**Comment by SerafimArts** [comment]
Done https://github.com/phplrt/phplrt/commit/6cc1467a4e6b31449be634b0bb8ec7259c059fbb
