### ISSUE TITLE
Any suggestion to have a parser trace

### ISSUE THREAD

**Issue by guiled** [phplrt/phplrt#9]
I have a grammar that should (theorically) parse an input, but doesn't !
The fact is I see a rule that "collide" with an other, that (theorically) it shouldn't…
The short resume of my grammar is :

```
A -> T x
B -> T y
```

With a typical input Rule B should be parsed, but the parser failed.
I change rule A like this
```
A -> T' x     // I put anything that won't parse
B -> T y
```
Like that, with the same input rule B is parsed as intended.

So I know there is something wrong somewhere and I can't figure out what. I'm looking for a way to see which rule is "entered" and "exited".

**Comment by SerafimArts** [comment]
```
new Parser($lexer, [
    Parser::CONFIG_STEP_REDUCER => function($ctx, $next) {
        try {
            echo 'Enter: ' . $ctx->getState() . "\n";
            return $next($ctx);
        } finally {
            echo 'Leave: ' . $ctx->getState() . "\n";
        }
    }
]);
```

Like this? =)

**Comment by guiled** [comment]
This is really cool ! Thank you ! It works for me, now I'm analyzing the log of more than 600 lines :-P

**Comment by SerafimArts** [comment]
At the end I want to see something like this:

![https://habrastorage.org/webt/xi/vm/5g/xivm5g5d640s54ni3urif6qsbl8.gif](https://habrastorage.org/webt/xi/vm/5g/xivm5g5d640s54ni3urif6qsbl8.gif)

But while there is no time to implement a similar package to visualize the work =(

**Comment by guiled** [comment]
That would be very useful.
With `Debbuger` class I see that the parser goes though a rule (that fails) and doesn't go through the following rule (that should pass). As I don't master phplrt yet, can you tell me where I should look at ?

The part that interests me in my grammar is
```
expression_term:
  expression_token()
  | function_call()
  | table_access()
;
```

The input is `b=a()[1]`

The Debugger log is (I reversed the order of rules (first is root node, last is currently parsed node)
```
----------------------------------------------------------------------------------------------------
   1. | b=a()[1]
      | block > assignation > expression_term > expression_token
      | stack(0) {  }
----------------------------------------------------------------------------------------------------
   1. | b=a()[1]
      | block < assignation < expression_term
      | stack(0) {  }
----------------------------------------------------------------------------------------------------
   1. | b=a()[1]
      | block > assignation > expression_term > function_call
      | stack(0) {  }
----------------------------------------------------------------------------------------------------
   1. | b=a()[1]
      | block > assignation > expression_term > function_call > function_call_arguments
      | stack(0) {  }
----------------------------------------------------------------------------------------------------
   1. | b=a()[1]
   +  | block < assignation < expression_term < function_call
      | stack(1) { function_call_arguments }
----------------------------------------------------------------------------------------------------
   1. | b=a()[1]
   +  | block < assignation < expression_term
      | stack(2) { function_call_arguments, function_call }
----------------------------------------------------------------------------------------------------
   1. | b=a()[1]
   +  | block < assignation
      | stack(3) { function_call_arguments, function_call, expression_term }
----------------------------------------------------------------------------------------------------
```

We can read here that it tries `assignation > expression_term > function_call > function_call_arguments` and goes up to root node, without trying `assignation > expression_term > table_access` node…
If I reverse the rule order in expression_term, it works for a `table_access` but fails with a `function_call` (ie `b=a[1]()`)

**Comment by SerafimArts** [comment]
It is worth noting that, unlike Hoa, there is no "state recovery". This is for speed, but not all grammars will work. 

> and goes up to root node, without trying `assignation > expression_term > table_access` node…

That is, under OR conditions, the first satisfying rule is selected. As you can see, "function_call" corresponds to the grammar. He will not try to check the rest of the rules, as already found a suitable one.

**Comment by SerafimArts** [comment]
I want to say that in your case it finds a function: `expression_term -> function_call -> function_call_arguments` and further analysis is carried out under the following conditions.

**Comment by guiled** [comment]
Thank you !

> That is, under OR conditions, the first satisfying rule is selected

Ok ! I understand now my problem.

So, with this feature I have no solution at all for my problem without modifying parser :-(

**Comment by SerafimArts** [comment]
> So, with this feature I have no solution at all for my problem without modifying parser :-(

There are always solutions. Here is an example implementation ISO/IEC 9899:TC2 (https://en.wikipedia.org/wiki/C99): https://gist.github.com/SerafimArts/b0a1579cd55961b49ab7e27080680517

**Comment by guiled** [comment]
Here is the grammar I use
https://github.com/guiled/PhpLrtLua/blob/func_table/LuaGrammar.pp2#L235-L281
(highlighted is the part of chained functions and tables)

The thing I am looking for to do is :
- I can write : `a()().b()()()[1]()[1]` or `a()().b[1]()()()[1]()` (any combination…). Ending with [x] is an array access, ending with () is a function call.
- table access can be on left side of assignation, function call can't. Both can be on the right side of assignation.

you can notice that I simplified the rule for arythmetics, because I notice that having a lot of level can decrease dramaticaly performance for long expression… So I decided to simplify the grammar to have a fast parser and put the complexity in the visitors (precedence)

**Comment by SerafimArts** [comment]
Not the best organization of grammar for the further construction of AST. But as you can see, it is quite possible...

```
<?php

use Phplrt\Compiler\Compiler;

require __DIR__ . '/vendor/autoload.php';

$compiler = new Compiler();
$compiler->load('
    %token T_DIGIT              \d+
    %token T_IDENTIFIER         \w+
    %token T_DOT                \.
    %token T_SQ_BRACKET_OPEN    \[
    %token T_SQ_BRACKET_CLOSE   \]
    %token T_RD_BRACKET_OPEN    \(
    %token T_RD_BRACKET_CLOSE   \)
    
    %skip  T_WHITESPACE         \s+
    
    #Expression
        : <T_IDENTIFIER> ExpressionContinuation()
          ExpressionChain()?
        ;
        
    #ExpressionContinuation
        : ExpressionSuffix()+
        ;
        
    #ExpressionChain
        : ::T_DOT:: Expression()
        ;
        
    #ExpressionSuffix
        : ArrayAccess()
        | FunctionCall()
        ;
    
    #ArrayAccess
        : ::T_SQ_BRACKET_OPEN::
            (<T_IDENTIFIER> | <T_DIGIT>)
          ::T_SQ_BRACKET_CLOSE::  
        ;
        
    #FunctionCall
        : ::T_RD_BRACKET_OPEN::
            // Arguments
          ::T_RD_BRACKET_CLOSE::
        ;
        
    #FunctionAccess
        : ::T_DOT::
        ;
');

echo $compiler->parse('a()().b()()()[1]()[1]');
```

**Comment by guiled** [comment]
> Not the best organization of grammar for the further construction of AST

Oh I know. "Je bidouille" we say in french. I'm messing around -_-

**Comment by guiled** [comment]
Hi ! Very good news ! With your advice I managed to have a parser that I'm sure at 95% it works for all case. I've taken antlr grammar.
Now I can work on the interpreter with confidence as I have made unit tests !
Moreover, I have taken some real world samples that all parse !
